version: "3"

services:

  ejabberd:
    build: ./docker/ejabberd/
    ports:
      - "5222:5222"
      - "5280:5280"
      - "5443:5443"

  postgres:
    build: ./docker/postgres/
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ejabberd

  mediasoup:
    build: ./mediasoup-server/
    environment:
      - "LOG_LEVEL=debug"
      - "DEBUG=mediasoup*"
      - "MEDIASOUP_TRANSPORT_ANNOUNCED_IP"
    ports:
      - "3500:3500"
      - "10000-10100:10000-10100"
